//GET usuario
###
GET http://localhost:3000/usuarios/user HTTP/1.1
Content-Type: application/json

{
    "email": "pepe.perez@iteso.mx",
    "password": "contraseña"
}

//POST USUARIO
###
POST http://localhost:3000/usuarios/create HTTP/1.1
content-type: application/json

{
    "name": "Pepe",
    "email": "pepe.perez@iteso.mx",
    "password": "contraseña",
    "cellphone": "3333333333",
    "residencia": "M",
    "alojamientos": ["12345"],
    "isHost": true,
    "description": "Si",
    "reservations": []
}

//PUT alojamiento en usuario
###
PUT http://localhost:3000/usuarios/add_alojamiento HTTP/1.1
Content-Type: application/json

{
    "id": "655ab5bd76d6c8f8ab3ff606",
    "alojamientos": ["67890", "27498"],
    "newAlojamiento": "12345"
}

//PUT reservacion en usuario
###
PUT http://localhost:3000/usuarios/add_reservacion HTTP/1.1
Content-Type: application/json

{
    "id": "655ab5bd76d6c8f8ab3ff606",
    "reservations": ["abcde", "fghij"],
    "newReservacion": "klmnñ"
}

//PUT account
###
PUT http://localhost:3000/usuarios/edit_account HTTP/1.1
Content-Type: application/json

{
    "id": "655ab30faee7cf1a2262bde5",
    "name": "Maigol",
    "residencia": "Los Cabos"
}

//DELETE alojamiento en usuario
###
DELETE http://localhost:3000/usuarios/delete_alojamiento HTTP/1.1
Content-Type: application/json

{
    "id": "655ab5bd76d6c8f8ab3ff606",
    "alojamientos": ["67890","27498","12345"],
    "toDelete": "27498"
}

//DELETE reservacion en usuario
###
DELETE http://localhost:3000/usuarios/delete_reservacion HTTP/1.1
Content-Type: application/json

{
    "id": "655ab5bd76d6c8f8ab3ff606",
    "reservations": ["abcde", "klmnñ"],
    "toDelete": "fghij"
}

//GET alojamientos
###
GET http://localhost:3000/alojamientos/get_all HTTP/1.1

//PUT alojamientos
###
PUT http://localhost:3000/alojamientos/edit_alojamiento HTTP/1.1
Content-Type: application/json

{
    "id":"655bd3f131b772faa40f6837",
    "title": "playera",
    "description": "detolles",
    "banos": 2,
    "beds": 1,
    "huespedes": 1,
    "rooms": 1,
    "categories": ["playa","alberca","novo"],
    "images": ["imagen1.png","imagen2.png"],
    "price": 1300,
    "estado": "Jalisco"
}

//POST alojamientos
###
POST http://localhost:3000/alojamientos/create HTTP/1.1
content-type: application/json

{
    "host":"655ab5bd76d6c8f8ab3ff606",
    "title": "Casa de playa",
    "description": "detalles",
    "banos": 2,
    "beds": 1,
    "huespedes": 1,
    "rooms": 1,
    "categories": ["playa","alberca"],
    "images": ["imagen1.png","imagen2.png"],
    "price": 1300,
    "estado": "Jalisco",
    "reservaciones": ""
}

//Delete alojamiento
###
DELETE http://localhost:3000/alojamientos/delete_alojamiento HTTP/1.1
Content-Type: application/json

{
    "id": "655be5ae71f17f6a8dd1c0e4",
    "host": "655ab5bd76d6c8f8ab3ff606"
}

//GET reservación
###
GET http://localhost:3000/reservaciones/reservation HTTP/1.1
Content-Type: application/json

{
    "id": "655bf7fa19ed6fe266c5cd32"
}

//POST reservation
###
POST http://localhost:3000/reservaciones/reserve HTTP/1.1
content-type: application/json

{
    "status": true,
    "fechaEntrada": "2023-12-05",
    "fechaSalida": "2023-12-08",
    "alojamiento": "655bd35c02857bf9cb0f504b",
    "host": "655ab5bd76d6c8f8ab3ff606",
    "cliente": "655ab30faee7cf1a2262bde5",
    "totalPrice": 3000
}

//DELETE reservacion
###
DELETE http://localhost:3000/reservaciones/delete HTTP/1.1
Content-Type: application/json

{
    "id": "655c169e79fd5d2b0fceaf0b",
    "cliente": "655ab30faee7cf1a2262bde5"
}