//---------------------------------------RUTAS SIN ADMIN--------------------------------------------------

//GET usuario
###
GET http://localhost:3000/sinAdmin/user?email=alberto.torres@iteso.mx&password=contraseña HTTP/1.1

//POST USUARIO
###
POST http://localhost:3000/sinAdmin/create HTTP/1.1
content-type: application/json

{
    "name": "Alan",
    "email": "alan.perez@iteso.mx",
    "password": "12345",
    "cellphone": "3333333333",
    "residencia": "M",
    "alojamientos": [],
    "isHost": true,
    "description": "Si",
    "reservations": []
}

//GET alojamientos
###
GET http://localhost:3000/sinAdmin/get_all HTTP/1.1

//GET filtered
###
GET http://localhost:3000/sinAdmin/get_filtered?categories[]=popular&categories[]=playa&estado=&title= HTTP/1.1

//---------------------------------------RUTAS CON ADMIN--------------------------------------------------------

//-------------------------------------------------USUARIO-------------------------------------------------------
//GET user por ID account
###
GET http://localhost:3000/usuarios/user HTTP/1.1
Content-Type: application/json
x-auth:admin

{
    "id": "655c190930349fcbf6f1ce23"
}

//PUT account
###
PUT http://localhost:3000/usuarios/edit_account HTTP/1.1
Content-Type: application/json
x-auth:admin

{
    "id": "655ab30faee7cf1a2262bde5",
    "name": "Miguel",
    "email": "alberto.torres@iteso.mx",
    "cellphone": "3330003330",
    "residencia": "Guadalajara",
    "description": "o get social media testimonials like these, keep your customers engaged with your social media accounts by posting regularly yourself"
}


//----------------------------------------------ALOJAMIENTO---------------------------------------------------
//PUT alojamientos
###
PUT http://localhost:3000/alojamientos/edit_alojamiento HTTP/1.1
Content-Type: application/json
x-auth:admin

{
    "id":"655e7dffc4b6d67fc525fd4e",
    "title": "Casa casi de Playa",
    "description": "detalles y precio",
    "banos": 3,
    "beds": 2,
    "huespedes": 4,
    "rooms": 1,
    "categories": ["Playa","Popular"],
    "images": ["imagen1.png","imagen1.png","imagen1.png","imagen1.png","imagen1.png"],
    "price": 1300,
    "estado": "Jalisco"
}

//POST alojamientos
###
POST http://localhost:3000/alojamientos/create HTTP/1.1
content-type: application/json
x-auth:admin

{
    "host":"655ab30faee7cf1a2262bde5",
    "title": "FFFF",
    "description": "detalles y precio",
    "banos": 3,
    "beds": 2,
    "huespedes": 4,
    "rooms": 1,
    "categories": ["Montaña","Playa"],
    "images": ["imagen1.png","imagen2.png"],
    "price": 1300,
    "estado": "Nuevo León",
    "reservaciones": ""
}

//Delete alojamiento
###
DELETE http://localhost:3000/alojamientos/delete_alojamiento HTTP/1.1
Content-Type: application/json
x-auth:admin

{
    "id": "655c1ce230349fcbf6f1ce51",
    "host": "655ab30faee7cf1a2262bde5"
}

###
GET http://localhost:3000/alojamientos/get_by_id?_id=655e7dffc4b6d67fc525fd4e HTTP/1.1
x-auth:admin



//-------------------------------------------------------RESERVACIÓN---------------------------------------------

//GET reservación
###
GET http://localhost:3000/reservaciones/reservation?_id=6562d49aa1161634798eac3d HTTP/1.1
x-auth:admin

//POST reservation
###
POST http://localhost:3000/reservaciones/reserve HTTP/1.1
content-type: application/json
x-auth:admin

{
    "status": false,
    "fechaEntrada": "2023-11-20",
    "fechaSalida": "2023-11-23",
    "alojamiento": "655d11305880faf62bb0a308",
    "host": "655ab5bd76d6c8f8ab3ff606",
    "cliente": "655ab30faee7cf1a2262bde5",
    "totalPrice": 3000
}

//DELETE reservacion
###
DELETE http://localhost:3000/reservaciones/delete HTTP/1.1
Content-Type: application/json
x-auth:admin

{
    "id": "655c1a5d30349fcbf6f1ce2f",
    "cliente": "655ab30faee7cf1a2262bde5"
}